<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdysTech.CredentialManager" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <PackageReference Include="StrongOf" />
    <PackageReference Include="System.Drawing.Common" Condition="!$([MSBuild]::IsOSPlatform('Windows'))" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Settings\UserControls\CredentialsControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>
